name: Prisma DB Push

on:
  push:
    branches:
      - main

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Prisma DB Push
        env:
          DATABASE_URL: 'prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTJiMTcyMjAtZWRlMS00NTQzLWFlM2ItNmEwNGM4MDI1MmQ2IiwidGVuYW50X2lkIjoiOWU0MDg3NWQxMGMxZTgyZDI5MjU3YTkxZGY3OWQzM2VjZGQ2NzM3NTc2YjRlNDQ1MDZjNGRjMTAwMzNhNjAxMCIsImludGVybmFsX3NlY3JldCI6IjU0Y2NhMTA5LTMyMzItNGRjMC1hODE5LTM1MTRjNzc1NzQxYSJ9.zPLu5re4Ur9TnMMRD3N5672cM3VwAzsFVTItx5d5y18'
        run: |
          npx prisma db push
