name: Test Database Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --force
      - name: Print DATABASE_URL
        run: echo $DATABASE_URL
      - name: Test database connection
        run: npx prisma db push
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
