name: Test Database Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --force
      - name: Test database connection
        env:
          DATABASE_URL: 'prisma+postgres://tborer:coding2025@accelerate.prisma-data.net:5432/resumeDB'
        run: npx prisma db push
