name: Test Environment

on:
  push:
    branches:
      - main
      - feature/github-actions

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t test-image .

      - name: Create test environment
        run: |
          docker-compose up -d
          sleep 10 # wait for services to start

      - name: Run tests
        run: |
          npm run test

      - name: Teardown test environment
        run: |
          docker-compose down
