name: Test Database Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: ./install-deps
      - name: Test database connection
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma db push
