YAML
name: Test Environment

on:
  push:
    branches:
      - feature/github-actions

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t my-app .
          docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-app
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app

      - name: Create test environment
        run: |
          docker-compose up -d
          sleep 10 # wait for services to start

      - name: Run tests
        run: |
          npm run test

      - name: Teardown test environment
        run: |
          docker-compose down
